# -----------------------------------------------------------------------------
# Makefile.targets
#
# We list the targets explicitly in here, in a separate file,
# in order to avoid modifying the main Makefile so much whenever
# we add or remove source files.
#
# -----------------------------------------------------------------------------

# main source files
common-cc := \
	src/io_dealii.cc \
	src/io_stl.cc \
	src/io_ucd.cc \
	src/mesh.cc \
	src/point_cloud.cc \
	src/tri2quad.cc \
	src/progress_timer.cc

common-h := \
	include/io_dealii.h \
	include/io_stl.h \
	include/io_ucd.h \
	include/mesh.h \
	include/point_cloud.h \
	include/tri2quad.h \
	include/progress_timer.h

# target source files from bin/ directory
bin-cc := \
	bin/bem_solve.cc \
	bin/fem_solve.cc \
	bin/mesh_info.cc

# target source files from tests/ directory
tests-cc := \
	tests/skull.cc \
	tests/sphere.cc \
	tests/sphere2.cc \
	tests/stacked_cubes.cc \
	tests/hello.cc

# -----------------------------------------------------------------------------
# vim: ft=make
