# -----------------------------------------------------------------------------
# Makefile.targets
#
# We list the targets explicitly in here, in a separate file,
# in order to avoid modifying the main Makefile so much whenever
# we add or remove source files.
#
# -----------------------------------------------------------------------------

# main source files
common-cc := \
	src/io_dealii.cc \
	src/io_stl.cc \
	src/io_ucd.cc \
	src/mesh.cc \
	src/point_cloud.cc \
	src/geometry_utils.cc \
	src/random_utils.cc \
	src/sphere_surface.cc \
	src/dipole_sources.cc \
	src/material_data.cc \
	src/bem_fwd_problem.cc \
	src/hptimer.cc \
	src/progress_timer.cc

common-h := \
	include/io_dealii.h \
	include/io_stl.h \
	include/io_ucd.h \
	include/mesh.h \
	include/point_cloud.h \
	include/geometry_utils.h \
	include/random_utils.h \
	include/sphere_surface.h \
	include/dipole_sources.h \
	include/material_data.h \
	include/bem_fwd_problem.h \
	include/nelder_mead.h \
	include/hptimer.h \
	include/progress_timer.h \
	include/config.h

# target source files from bin/ directory
bin-cc := \
	bin/bem_solve.cc \
	bin/select_electrodes.cc \
	bin/measure_electrodes.cc \
	bin/bem_inverse_solver.cc \
	bin/stl_to_ucd.cc \
	bin/tri_to_quad.cc \
	bin/set_material_id.cc \
	bin/merge_ucd_files.cc \
	bin/mesh_info.cc \
	bin/spherical_head_model.cc \
	bin/fem_solve.cc
ifeq ($(DEAL_II_USE_MPI),yes)
bin-cc += \
	bin/mpi_jobarray.cc
endif

# target source files from tests/ directory
tests-cc := \
	tests/hex_inverse_solver.cc \
	tests/bone_stl_to_ucd.cc \
	tests/mat_for_bone.cc \
	tests/mat_for_artery.cc \
	tests/mat_for_doublesphere.cc \
	tests/merge_bone_artery_ucd.cc \
	tests/test_simplex_search.cc \
	tests/test_sphere_surface.cc \
	tests/test_load_mesh.cc \
	tests/test_vcg_load_mesh.cc \
	tests/test_dipoles.cc \
	tests/test_materials.cc \
	tests/test_functor.cc \
	tests/test_random.cc \
	tests/test_ptree.cc \
	tests/test_hptimer.cc \
	tests/test_octree.cc \
	tests/test_msgpack.cc \
	tests/test_zmq_server.cc \
	tests/test_zmq_client.cc \
	tests/test_po.cc \
	tests/hello.cc
ifeq ($(DEAL_II_USE_MPI),yes)
tests-cc += \
	tests/mpi_job_queue.cc \
	tests/mpi_primes.cc \
	tests/mpi_hello2.cc \
	tests/mpi_hello.cc
endif

# -----------------------------------------------------------------------------
# vim: ft=make
